config/routes.rb
TaxAdvisor::Application.routes.draw do
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_scope :admin_user do
  end

  devise_for :users

  resources :categories do
    collection do
      get 'user_categories'
    end
  end

  resources :pricings do
    collection do
      get 'user_pricing'
    end
  end

  resources :bankings

  resources :mailings

  
  
  get "home/index"
  get "home/about_us"
  get "home/our_clients"
  get "home/tax_guide"
  get "home/services"
  get "home/contacts"
  get "home/payment"
  get "home/alert"
  get "home/pricing"
  

  root :to => 'home#index'
  

  

end

app/models/account_type.rb
class AccountType < ActiveRecord::Base
  attr_accessible :name, :status
  
  has_many :users
  
  ADMIN = 1
  CLIENT = 2
  
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  
  attr_accessible :avatar, :remote_avatar_url
  
  belongs_to :mailing
  
  mount_uploader :avatar, AvatarUploader
  
end

app/models/banking.rb
class Banking < ActiveRecord::Base
  attr_accessible :name, :account_no, :address1, :address2, :city, :country, :state, :zip_code, :status
  
  
  validates :name, :presence => true
  validates :account_no, :presence => true, :uniqueness => true
  validates :address1, :presence => true
  validates :city, :presence => true
  validates :state, :presence => true
  validates :country, :presence => true
  validates :zip_code, :presence => true
  validates_inclusion_of :status, :in => [true, false]
    
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :name, :status, :pricing_ids
  
  has_and_belongs_to_many :users
  
  has_and_belongs_to_many :pricings
  accepts_nested_attributes_for :pricings
  
  validates :name, :presence => true
  validates :description, :presence => true
  validates_inclusion_of :status, :in => [true, false]
  
end

app/models/mailing.rb
class Mailing < ActiveRecord::Base
  attr_accessible :body, :email, :from, :subject, :avatar, :attachments_attributes
  
  has_many :attachments, :dependent => :destroy
  accepts_nested_attributes_for :attachments, :allow_destroy => true
  
  validates :email, :presence => true
end

app/models/pricing.rb
class Pricing < ActiveRecord::Base
  attr_accessible :month, :rate, :status, :time_period
  
  has_and_belongs_to_many :categories
  
  validates :month, :presence => true
  validates :time_period, :numericality => { :only_integer => true, :greater_than_or_equal_to => 0 }
  validates :rate, :numericality => { :greater_than_or_equal_to => 0 }
  validates_inclusion_of :status, :in => [true, false]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable,
  # :lockable, :timeoutable and :omniauthable
 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable
  
  # Setup accessible (or protected) attributes for your model
  attr_accessible :first_name, :last_name, :account_type_id, :email, :password, :password_confirmation, :remember_me, :category_ids
  
  
  
  
  
#  attr_accessible  :email, :first_name, :last_name, :password, :password_confirmation
#  
#  has_secure_password
#  
  belongs_to :account_type
  
  has_and_belongs_to_many :categories
  accepts_nested_attributes_for :categories
#  
#  
#  
#  
#  validates :first_name, :presence => true
#  validates :last_name, :presence => true
#  
#  validates :email, :presence => true, :uniqueness => true
#  validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
#
#  validates :password, :presence => true, :on => :create
#  validates_size_of :password, :within => 6..15, :on => :create
#  before_create { generate_token(:auth_token) }
#  
#  validates :account_type_id, :presence => true
#  
#  
#  
#  
#  def full_name
#    "#{self.first_name }"+" "+ "#{self.last_name}".camelize
#  end
#  
#  def send_password_reset
#    generate_token(:password_reset_token)
#    self.password_reset_sent_at = Time.zone.now
#    save!
#    UserMailer.password_reset(self).deliver
#  end
#
#
#  def generate_token(column)
#    begin
#      
#      self[column] = SecureRandom.urlsafe_base64
#    end while User.exists?(column => self[column])
#  end
  
end

app/controllers/bankings_controller.rb
class BankingsController < InheritedResources::Base
  
  before_filter :authenticate_user!
  #layout :user_layout
  
end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base
  
  before_filter :authenticate_user!
  #layout :user_layout
  def user_categories
    @categories = current_user.categories.all
    #raise @categories.inspect
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #layout :user_layout
  
  def index
  end
  
  def about_us
    
  end
  
  def our_clients
    
  end
  
  def tax_guide
    
  end
 
  def services
    
  end
 
  def contacts
    
  end
  def payment

  end
  def alert

  end
  def pricing

  end
   
end

app/controllers/mailings_controller.rb
class MailingsController < ApplicationController
  # GET /mailings
  # GET /mailings.json
 
  before_filter :authenticate_user!
  #layout :user_layout
  
  def index
    @mailings = Mailing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mailings }
    end
  end

  # GET /mailings/1
  # GET /mailings/1.json
  def show
    @mailing = Mailing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mailing }
    end
  end

  # GET /mailings/new
  # GET /mailings/new.json
  def new
    @mailing = Mailing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mailing }
    end
  end

  # GET /mailings/1/edit
  def edit
    @mailing = Mailing.find(params[:id])
  end

  # POST /mailings
  # POST /mailings.json
  def create
    @mailing = Mailing.new(params[:mailing])
    
    #raise @mailing.inspect
    respond_to do |format|
     
      if @mailing.save
        MailingMailer.compose_mail(@mailing).deliver
        format.html { redirect_to new_mailing_path, notice: "Mail was successfully sent to #{@mailing.email}." }
        format.json { render json: @mailing, status: :created, location: @mailing }
      else
        format.html { render action: "new" }
        format.json { render json: @mailing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mailings/1
  # PUT /mailings/1.json
  def update
    @mailing = Mailing.find(params[:id])

    respond_to do |format|
      if @mailing.update_attributes(params[:mailing])
        format.html { redirect_to @mailing, notice: 'Mailing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mailing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mailings/1
  # DELETE /mailings/1.json
  def destroy
    @mailing = Mailing.find(params[:id])
    @mailing.destroy

    respond_to do |format|
      format.html { redirect_to mailings_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pricings_controller.rb
class PricingsController < InheritedResources::Base
  
  before_filter :authenticate_user!
  #layout :user_layout
  
  def user_pricings
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bankings_helper.rb
module BankingsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mailings_helper.rb
module MailingsHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/pricings_helper.rb
module PricingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about_us.html.erb
 <%  content_for :header_image do %>
 <%= image_tag('about_us_1.jpg', :style => 'width:100%;margin-top:-10px;height:200px !important;') %>
 <% end %>


<div class="row">
  <h3>
    About Us
  </h3>
  <p class="lead">
   

We are a team of highly qualified and experienced analysts, who deliver their expertise in providing stock market calls for traders which include tips like Stock Cash Tips, Commodity Tips, MCX Tips, Equity Tips and Intraday Tips. All services are provided through SMS and Instant Messenger.
  </p>
</div>

app/views/home/alert.html.erb
 <%  content_for :header_image do %>
 <%= image_tag('alert_1.jpg', :style => 'width:100%;margin-top:-10px;height:200px !important;') %>
 <% end %>

<div class="row">
  <h3>
    Alert
  </h3>
  <p class="lead">


We are a team of highly qualified and experienced analysts, who deliver their expertise in providing stock market calls for traders which include tips like Stock Cash Tips, Commodity Tips, MCX Tips, Equity Tips and Intraday Tips. All services are provided through SMS and Instant Messenger.
  </p>
</div>

app/views/home/contacts.html.erb
<%  content_for :header_image do %>
 <%= image_tag('header_contact.jpg', :style => 'width:100%;margin-top:-10px;height:200px !important;') %>
 <% end %>

<div class="row">
  <h3>
    Contact US
  </h3>
  <p class="lead">


We are a team of highly qualified and experienced analysts, who deliver their expertise in providing stock market calls for traders which include tips like Stock Cash Tips, Commodity Tips, MCX Tips, Equity Tips and Intraday Tips. All services are provided through SMS and Instant Messenger.
  </p>
</div>

app/views/home/index.html.erb
 <%  content_for :header_image do %>
 <%= image_tag('financial_services.jpg', :style => 'width:100%;margin-top:-10px;height:200px;') %>
 <% end %>
<div class="row">
  <div class="span4" style="background:#f1f1f1;">
    <div style="min-height:500px;">
       <div class="media-body">
    <h3 class="media-heading" style="text-align:center;"><%= image_tag('gagar.jpg', :style => 'width:100%;height:50px;')%> </h3>
    
    <div class="media">
      <table class="table table-bordered" style="background:#ffffff;">
       <tr>
         <td>BSE</td><td>Monday, March 04, 2013 07:40:09 PM, BSE Ticker</td>
       </tr>
       <tr>
         <td>NSE</td><td>Monday, March 04, 2013 07:40:09 PM, BSE Ticker</td>
       </tr>
       <tr>
         <td>BSE</td><td>Monday, March 04, 2013 07:40:09 PM, BSE Ticker</td>
       </tr>
       <tr>
         <td>NSE</td><td>Monday, March 04, 2013 07:40:09 PM, BSE Ticker</td>
       </tr>
       <tr>
         <td>BSE</td><td>Monday, March 04, 2013 07:40:09 PM, BSE Ticker</td>
       </tr>
       <tr>
         <td>NSE</td><td>Monday, March 04, 2013 07:40:09 PM, BSE Ticker</td>
       </tr>
       <tr>
         <td>BSE</td><td>Monday, March 04, 2013 07:40:09 PM, BSE Ticker</td>
       </tr>
       <tr>
         <td>NSE</td><td>Monday, March 04, 2013 07:40:09 PM, BSE Ticker</td>
       </tr>
     </table>
    </div>
  </div>
    </div>
  </div>
  <div class="span8" style="background:#f2f2f2;">
    <div style="min-height:500px;">
      <div class="row">
        <div style="min-height:300px;margin-top:40px;">
          <div class="span3">
            <h3 style="margin-left:20px;">
              WHAT ASSITANCE DOES
            </h3>
        </div>
          <div class="span5">
          <p class="lead">Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus.Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctusVivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus</p>
        </div>
          
        </div>
      </div>
      <div class="row">
        <div class="span6">
          <h3 style="margin-left:20px;">
              IMPORTANT THINGS ABOUT MARKET
          </h3>
          <p class="lead" style="margin-left:20px;">Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis</p>
        </div>
        <div class="span2">
          <%= link_to "Sign up","",:class =>'btn btn-info' , :style =>"height:100px;width:100px;"%>
        </div>
      </div>
    </div>
  </div>
 
</div>

app/views/home/our_clients.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "our_clients.html" %>

app/views/home/payment.html.erb
 <%  content_for :header_image do %>
 <%= image_tag('payment.jpg', :style => 'width:100%;margin-top:-10px;height:200px !important;') %>
 <% end %>

<div class="row">
  <h3>
    Payment
  </h3>
  <p class="lead">


We are a team of highly qualified and experienced analysts, who deliver their expertise in providing stock market calls for traders which include tips like Stock Cash Tips, Commodity Tips, MCX Tips, Equity Tips and Intraday Tips. All services are provided through SMS and Instant Messenger.
  </p>
</div>

app/views/home/pricing.html.erb
 <%  content_for :header_image do %>
 <%= image_tag('pricing.jpg', :style => 'width:100%;margin-top:-10px;height:200px !important;') %>
 <% end %>

<div class="row">
  <h3>
    Pricing
  </h3>
  <p class="lead">


We are a team of highly qualified and experienced analysts, who deliver their expertise in providing stock market calls for traders which include tips like Stock Cash Tips, Commodity Tips, MCX Tips, Equity Tips and Intraday Tips. All services are provided through SMS and Instant Messenger.
  </p>
</div>

app/views/home/services.html.erb
 <%  content_for :header_image do %>
 <%= image_tag('services.jpg', :style => 'width:100%;margin-top:-10px;height:200px !important;') %>
 <% end %>

<div class="row">
  <h3>
    Services
  </h3>
  <p class="lead">


We are a team of highly qualified and experienced analysts, who deliver their expertise in providing stock market calls for traders which include tips like Stock Cash Tips, Commodity Tips, MCX Tips, Equity Tips and Intraday Tips. All services are provided through SMS and Instant Messenger.
  </p>
</div>

app/views/home/tax_guide.html.erb
 <%  content_for :header_image do %>
 <%= image_tag('alert_1.jpg', :style => 'width:100%;margin-top:-10px;height:200px !important;') %>
 <% end %>

<div class="row">
  <h3>
    Alert
  </h3>
  <p class="lead">


We are a team of highly qualified and experienced analysts, who deliver their expertise in providing stock market calls for traders which include tips like Stock Cash Tips, Commodity Tips, MCX Tips, Equity Tips and Intraday Tips. All services are provided through SMS and Instant Messenger.
  </p>
</div>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>

    <div class="control-group">
      <%= f.label :first_name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :first_name, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :last_name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :last_name, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :email, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :email, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :password, :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password, :class => 'text_field', :placeholder =>"Password" %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :password_confirmation, :class => 'control-label' %>
      <div class="controls">
        <%= f.password_field :password_confirmation, :class => 'text_field', :placeholder =>"Password Confirmaton" %>
      </div>
    </div>

    <% if is_admin? %>
      <div class="control-group">
        <%= f.label :member_type, :class => 'control-label' %>
        <div class="controls">
          Admin
          <%= f.radio_button :account_type_id,1 %>
          Client
          <%= f.radio_button :account_type_id,2 %>
        </div>
      </div>
    <% end %>

    <div class="control-group ">
      <%= f.label :categories, :class => 'control-label' %>
      <div class="controls">
        <%= hidden_field_tag "user[category_ids][]", nil%>
        <% Category.all.each do |category| %>
          <label class="checkbox inline">
            <%= check_box_tag "user[category_ids][]", category.id, @user.category_ids.include?(category.id), id: dom_id(category) %>
            <%= category.name %>
          </label>
        <% end %>
      </div>
    </div>


    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
        users_path, :class => 'btn' %>
    </div>

<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:password_digest) %></th>
      <th><%= model_class.human_attribute_name(:account_type_id) %></th>
      <th><%= model_class.human_attribute_name(:auth_token) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.account_type.name %></td>
        <td><%= user.auth_token %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%  content_for :header_image do %>
 <%= image_tag('financial_services.jpg', :style => 'width:100%;margin-top:-10px;height:200px;') %>
 <% end %>
<%- model_class = User -%>
<div class="page-header">
  <h3><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h3>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:first_name) %>:</strong></dt>
  <dd><%= @user.first_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @user.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:account_type_id) %>:</strong></dt>
  <dd><%= @user.account_type.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:auth_token) %>:</strong></dt>
  <dd><%= @user.auth_token %></dd>
  <dt><strong>Categories:</strong></dt>
  <% @user.categories.each do |category| %>
  <dd><%=  link_to category.name, category_path(category)  %></dd>
  <% end %>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>