config/routes.rb
TaxAdvisor::Application.routes.draw do
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_scope :admin_user do
  end

  devise_for :users

  resources :categories do
    collection do
      get 'user_categories'
    end
  end

  resources :pricings do
    collection do
      get 'user_pricing'
    end
  end

  resources :bankings

  resources :mailings

  
  
  get "home/index"
  get "home/about_us"
  get "home/our_clients"
  get "home/tax_guide"
  get "home/services"
  get "home/contacts"
  get "home/payment"
  get "home/alert"
  get "home/pricing"
  

  root :to => 'home#index'
  

  

end

app/models/banking.rb
class Banking < ActiveRecord::Base
  attr_accessible :name, :account_no, :address1, :address2, :city, :country, :state, :zip_code, :status
  
  
  validates :name, :presence => true
  validates :account_no, :presence => true, :uniqueness => true
  validates :address1, :presence => true
  validates :city, :presence => true
  validates :state, :presence => true
  validates :country, :presence => true
  validates :zip_code, :presence => true
  validates_inclusion_of :status, :in => [true, false]
    
end

app/controllers/bankings_controller.rb
class BankingsController < InheritedResources::Base
  
  before_filter :authenticate_user!
  #layout :user_layout
  
end

app/helpers/bankings_helper.rb
module BankingsHelper
end

app/views/bankings/_form.html.erb
<%= form_for @banking, :html => { :class => 'form-horizontal' } do |f| %>

  <div class="control-group">
    <%= f.label :name, "Bank Name", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :account_no, "Account Number", :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :account_no, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address1, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address1, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address2, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :address2, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :city, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :city, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :state, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :state, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :country, :class => 'control-label' %>
    <div class="controls">
      <%=  country_select("banking", "country", [ "United Kingdom", "France", "Germany" ], {:prompt=> 'Please select a country'}) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :zip_code, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :zip_code, :class => 'number_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :status, :class => 'control-label' %>
    <div class="controls">
      Active
      <%= f.radio_button :status, true %>
      Inactive
      <%= f.radio_button :status, false %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
      bankings_path, :class => 'btn' %>
  </div>
<% end %>

app/views/bankings/edit.html.erb
<%- model_class = Banking -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bankings/index.html.erb
<%- model_class = Banking -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:account_no) %></th>
      <th><%= model_class.human_attribute_name(:address1) %></th>
      <th><%= model_class.human_attribute_name(:address2) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <th><%= model_class.human_attribute_name(:country) %></th>
      <th><%= model_class.human_attribute_name(:zip_code) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @bankings.each do |banking| %>
      <tr>
        <td><%= link_to banking.id, banking_path(banking) %></td>
        <td><%= banking.name %></td>
        <td><%= banking.account_no %></td>
        <td><%= banking.address1 %></td>
        <td><%= banking.address2 %></td>
        <td><%= banking.city %></td>
        <td><%= banking.state %></td>
        <td><%= banking.country %></td>
        <td><%= banking.zip_code %></td>
        <% if banking.status %>
          <td>Active</td>
        <% else %>
          <td>Inactive</td>
        <% end %>
        <td><%=l banking.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
            edit_banking_path(banking), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
            banking_path(banking),
            :method => :delete,
            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
            :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
  new_banking_path,
  :class => 'btn btn-primary' %>

app/views/bankings/new.html.erb
<%- model_class = Banking -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bankings/show.html.erb
<%- model_class = Banking -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @banking.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:account_no) %>:</strong></dt>
  <dd><%= @banking.account_no %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address1) %>:</strong></dt>
  <dd><%= @banking.address1 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address2) %>:</strong></dt>
  <dd><%= @banking.address2 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @banking.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
  <dd><%= @banking.state %></dd>
  <dt><strong><%= model_class.human_attribute_name(:country) %>:</strong></dt>
  <dd><%= @banking.country %></dd>
  <dt><strong><%= model_class.human_attribute_name(:zip_code) %>:</strong></dt>
  <dd><%= @banking.zip_code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <% if @banking.status %>
    <dd>Active</dd>
  <% else %>
    <dd>Inactive</dd>
  <% end %>

</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
    bankings_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
    edit_banking_path(@banking), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
    banking_path(@banking),
    :method => 'delete',
    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
    :class => 'btn btn-danger' %>
</div>