config/routes.rb
TaxAdvisor::Application.routes.draw do
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_scope :admin_user do
  end

  devise_for :users

  resources :categories do
    collection do
      get 'user_categories'
    end
  end

  resources :pricings do
    collection do
      get 'user_pricing'
    end
  end

  resources :bankings

  resources :mailings

  
  
  get "home/index"
  get "home/about_us"
  get "home/our_clients"
  get "home/tax_guide"
  get "home/services"
  get "home/contacts"
  get "home/payment"
  get "home/alert"
  get "home/pricing"
  

  root :to => 'home#index'
  

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :name, :status, :pricing_ids
  
  has_and_belongs_to_many :users
  
  has_and_belongs_to_many :pricings
  accepts_nested_attributes_for :pricings
  
  validates :name, :presence => true
  validates :description, :presence => true
  validates_inclusion_of :status, :in => [true, false]
  
end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base
  
  before_filter :authenticate_user!
  #layout :user_layout
  def user_categories
    @categories = current_user.categories.all
    #raise @categories.inspect
  end
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category, :html => { :class => 'form-horizontal' } do |f| %>
  <% if is_admin? %>  
    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :description, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :description, :class => 'text_area' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :status, :class => 'control-label' %>
      <div class="controls">
        Active
        <%= f.radio_button :status, true %>
        Inactive
        <%= f.radio_button :status, false %>
      </div>
    </div>
    <!--
      <div class="control-group">
    <%= f.label :status, :class => 'control-label' %>
        <div class="controls">
    <%= f.check_box :status, :class => 'check_box' %>
        </div>
      </div>
    -->
  <% else %>

    <dl class="dl-horizontal">
      <dt><strong>Name:</strong></dt>
      <dd><%= @category.name %></dd>
      <dt><strong>Description:</strong></dt>
      <dd><%= @category.description %></dd>
      <dt><strong>Status:</strong></dt>
      <% if @category.status %>
        <dd>Active</dd>
      <% else %>
        <dd>Inactive</dd>
      <% end %>
    </dl>

    <div class="control-group ">
      <%= f.label :pricings, :class => 'control-label' %>
      <div class="controls">
        <%= hidden_field_tag "category[pricing_ids][]", nil%>
        <% Pricing.all.each do |pricing| %>
          <label class="checkbox inline">
            <%= check_box_tag "category[pricing_ids][]", pricing.id, @category.pricing_ids.include?(pricing.id), id: dom_id(pricing) %>
            <%= pricing.month %>
          </label>
        <% end %>
      </div>
    </div>
  <% end %>

  <% if is_admin? %>
    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
        categories_path, :class => 'btn' %>
    </div>
    <% else %>
    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
    </div>
  <% end %>
<% end %>

app/views/categories/edit.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/categories/index.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.id, category_path(category) %></td>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <% if category.status %>
          <td>Active</td>
        <% else %>
          <td>Inactive</td>
        <% end %>
        <td><%=l category.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_category_path(category), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      category_path(category),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_category_path,
            :class => 'btn btn-primary' %>

app/views/categories/new.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/categories/show.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @category.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @category.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <% if @category.status %>
    <dd>Active</dd>
  <% else %>
    <dd>Inactive</dd>
  <% end %>
    <dt><strong>Pricings:</strong></dt>
  <% @category.pricings.each do |pricing| %>
  <dd><%=  link_to pricing.month, pricing_path(pricing)  %></dd>
  <% end %>
</dl>
<% if is_admin? %>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              categories_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_category_path(@category), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              category_path(@category),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>
<% else %>

<div class="form-actions">
  <%= link_to 'Add Pricing', edit_category_path(@category), :class => 'btn' %>
</div>
<% end %>

app/views/categories/user_categories.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<h3><%= model_class.human_attribute_name(:name) %>:</h3>
<dl class="dl-horizontal">
  <% @categories.each do |category| %>
  <dd><strong><%=  link_to category.name, category_path(category)  %></strong></dd>
  <% end %>
</dl>