config/routes.rb
TaxAdvisor::Application.routes.draw do
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_scope :admin_user do
  end

  devise_for :users

  resources :categories do
    collection do
      get 'user_categories'
    end
  end

  resources :pricings do
    collection do
      get 'user_pricing'
    end
  end

  resources :bankings

  resources :mailings

  
  
  get "home/index"
  get "home/about_us"
  get "home/our_clients"
  get "home/tax_guide"
  get "home/services"
  get "home/contacts"
  get "home/payment"
  get "home/alert"
  get "home/pricing"
  

  root :to => 'home#index'
  

  

end

app/models/account_type.rb
class AccountType < ActiveRecord::Base
  attr_accessible :name, :status
  
  has_many :users
  
  ADMIN = 1
  CLIENT = 2
  
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  
  attr_accessible :avatar, :remote_avatar_url
  
  belongs_to :mailing
  
  mount_uploader :avatar, AvatarUploader
  
end

app/models/banking.rb
class Banking < ActiveRecord::Base
  attr_accessible :name, :account_no, :address1, :address2, :city, :country, :state, :zip_code, :status
  
  
  validates :name, :presence => true
  validates :account_no, :presence => true, :uniqueness => true
  validates :address1, :presence => true
  validates :city, :presence => true
  validates :state, :presence => true
  validates :country, :presence => true
  validates :zip_code, :presence => true
  validates_inclusion_of :status, :in => [true, false]
    
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :name, :status, :pricing_ids
  
  has_and_belongs_to_many :users
  
  has_and_belongs_to_many :pricings
  accepts_nested_attributes_for :pricings
  
  validates :name, :presence => true
  validates :description, :presence => true
  validates_inclusion_of :status, :in => [true, false]
  
end

app/models/mailing.rb
class Mailing < ActiveRecord::Base
  attr_accessible :body, :email, :from, :subject, :avatar, :attachments_attributes
  
  has_many :attachments, :dependent => :destroy
  accepts_nested_attributes_for :attachments, :allow_destroy => true
  
  validates :email, :presence => true
end

app/models/pricing.rb
class Pricing < ActiveRecord::Base
  attr_accessible :month, :rate, :status, :time_period
  
  has_and_belongs_to_many :categories
  
  validates :month, :presence => true
  validates :time_period, :numericality => { :only_integer => true, :greater_than_or_equal_to => 0 }
  validates :rate, :numericality => { :greater_than_or_equal_to => 0 }
  validates_inclusion_of :status, :in => [true, false]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable,
  # :lockable, :timeoutable and :omniauthable
 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable
  
  # Setup accessible (or protected) attributes for your model
  attr_accessible :first_name, :last_name, :account_type_id, :email, :password, :password_confirmation, :remember_me, :category_ids
  
  
  
  
  
#  attr_accessible  :email, :first_name, :last_name, :password, :password_confirmation
#  
#  has_secure_password
#  
  belongs_to :account_type
  
  has_and_belongs_to_many :categories
  accepts_nested_attributes_for :categories
#  
#  
#  
#  
#  validates :first_name, :presence => true
#  validates :last_name, :presence => true
#  
#  validates :email, :presence => true, :uniqueness => true
#  validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
#
#  validates :password, :presence => true, :on => :create
#  validates_size_of :password, :within => 6..15, :on => :create
#  before_create { generate_token(:auth_token) }
#  
#  validates :account_type_id, :presence => true
#  
#  
#  
#  
#  def full_name
#    "#{self.first_name }"+" "+ "#{self.last_name}".camelize
#  end
#  
#  def send_password_reset
#    generate_token(:password_reset_token)
#    self.password_reset_sent_at = Time.zone.now
#    save!
#    UserMailer.password_reset(self).deliver
#  end
#
#
#  def generate_token(column)
#    begin
#      
#      self[column] = SecureRandom.urlsafe_base64
#    end while User.exists?(column => self[column])
#  end
  
end

app/controllers/bankings_controller.rb
class BankingsController < InheritedResources::Base
  
  before_filter :authenticate_user!
  #layout :user_layout
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #layout :user_layout
  
  def index
  end
  
  def about_us
    
  end
  
  def our_clients
    
  end
  
  def tax_guide
    
  end
 
  def services
    
  end
 
  def contacts
    
  end
  def payment

  end
  def alert

  end
  def pricing

  end
   
end

app/controllers/mailings_controller.rb
class MailingsController < ApplicationController
  # GET /mailings
  # GET /mailings.json
 
  before_filter :authenticate_user!
  #layout :user_layout
  
  def index
    @mailings = Mailing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mailings }
    end
  end

  # GET /mailings/1
  # GET /mailings/1.json
  def show
    @mailing = Mailing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mailing }
    end
  end

  # GET /mailings/new
  # GET /mailings/new.json
  def new
    @mailing = Mailing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mailing }
    end
  end

  # GET /mailings/1/edit
  def edit
    @mailing = Mailing.find(params[:id])
  end

  # POST /mailings
  # POST /mailings.json
  def create
    @mailing = Mailing.new(params[:mailing])
    
    #raise @mailing.inspect
    respond_to do |format|
     
      if @mailing.save
        MailingMailer.compose_mail(@mailing).deliver
        format.html { redirect_to new_mailing_path, notice: "Mail was successfully sent to #{@mailing.email}." }
        format.json { render json: @mailing, status: :created, location: @mailing }
      else
        format.html { render action: "new" }
        format.json { render json: @mailing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mailings/1
  # PUT /mailings/1.json
  def update
    @mailing = Mailing.find(params[:id])

    respond_to do |format|
      if @mailing.update_attributes(params[:mailing])
        format.html { redirect_to @mailing, notice: 'Mailing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mailing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mailings/1
  # DELETE /mailings/1.json
  def destroy
    @mailing = Mailing.find(params[:id])
    @mailing.destroy

    respond_to do |format|
      format.html { redirect_to mailings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bankings_helper.rb
module BankingsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mailings_helper.rb
module MailingsHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/pricings_helper.rb
module PricingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    <p class="muted credit"> <a href="#">Your Company corp @ 2006 </a> | <a href="#">Privacy policy</a></p>
  </div>
</div>

app/views/layouts/_head_tag_element.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><%= content_for?(:title) ? yield(:title) : "Tax Advisor" %></title>
<meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Tax Advisor" %>">
<%= stylesheet_link_tag "application", :media => "all" %>
<%= javascript_include_tag "application" %>
<%= javascript_include_tag :defaults, "nested_form" %>
<%= csrf_meta_tags %>
<%= yield(:head) %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</a>
<%#= link_to "HOME", home_index_path, :class => 'brand' %>
<div class="nav-collapse" style="float:right;">
  <ul class="nav">
    <li><%= link_to "HOME", home_index_path %></li>
    <li><%= link_to "ABOUT US", home_about_us_path %></li>
    <li><%= link_to "SERVICES", home_services_path %></li>
    <li><%= link_to "ALERTS", home_alert_path %></li>
    <li><%= link_to "PAYMENTS", home_payment_path %></li>
    <li><%= link_to "PRICING", home_pricing_path %></li>
    <li><%= link_to "CONTACT US", home_contacts_path %></li>
    <% if user_signed_in? %>
      <li>
        <ul class="nav nav-pills">
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              MENU
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "CATEGORY", user_categories_categories_path %></li>
              <li><%= link_to "PRICING", pricings_path %></li>
            </ul>
          </li>
        </ul>
      </li>
      <li><%= link_to  current_user.email, edit_user_registration_path %></li>
      <li><%= link_to "SIGN OUT", destroy_user_session_path, :method => :delete %></li>
    <% else %>
      <li><%= link_to "SIGN IN", new_user_session_path %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tax Advisor</title>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body  style="background-color:grey;">

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <img src="/assets/logo.png"   style="height:50px;width:100px;" />
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
<%#= link_to "HOME", home_index_path, :class => 'brand' %>
          <div class="nav-collapse" style="float:right;">
            <ul class="nav">
              <li><%= link_to "HOME", home_index_path %></li>
              <li><%= link_to "ABOUT US", home_about_us_path %></li>
              <li><%= link_to "SERVICES", home_services_path %></li>
              <li><%= link_to "ALERTS", home_alert_path %></li>
              <li><%= link_to "PAYMENTS", home_payment_path %></li>
              <li><%= link_to "PRICING", home_pricing_path %></li>
              <li><%= link_to "CONTACT US", home_contacts_path %></li>
              <% if is_admin? %>
                <li>
                  <ul class="nav nav-pills">
                    <li class="dropdown">
                      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        MENU
                        <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu">
                        <li><%= link_to "MAILING", new_mailing_path %></li>
                        <li><%= link_to "BANKING", bankings_path %></li>
                        <li><%= link_to "CATEGORY", categories_path %></li>
                        <li><%= link_to "PRICING", pricings_path %></li>
                      </ul>
                    </li>
                  </ul>
                </li>
              <% end %>
              <% if is_login? %>
                <li><%= link_to current_user.full_name.upcase, user_path(current_user) %></li>
                <li><%= link_to "LOG OUT", logout_path %></li>
              <% else %>
                <li><%= link_to "SIGN UP", signup_path %></li>
                <li><%= link_to "LOG IN", login_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>


    <div class="container" id="container">
      <div class="row">

        <div class="span12">
          <%= yield :header_image %>

        </div> 
        <div class="span12" id="rotate"  style="background:#f0f0f0;color:red;margin-top: 3px;margin-bottom: 3px;padding-top:3px;padding-bottom:3px;">
          <marquee id="FutureMarquee" onmouseup="this.style.cursor=" default''="" onmouseover="this.stop();" onmouseout="this.start();" truespeed="truespeed" scrollamount="1" scrolldelay="20" width="100%" style="font-weight:bold;color:#000; padding-top:2px; display:block;"> Market Pundit Money Making Mantra <strong style="color:green">|</strong> Market Pundit Money Making Mantra <strong style="color:green">|</strong> Market Pundit Money Making MantraMarket Pundit Money Making Mantra <strong style="color:green">|</strong> Market Pundit Money Making Mantra <strong style="color:green">|</strong> Market Pundit Money Making Mantra</marquee>
        </div>
      </div>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <div class="row">
        <div class="span12">
          <%= yield %>
        </div>
      </div>
    </div>


    <div id="footer">
      <div class="container">
        <p class="muted credit"> <a href="#">Your Company corp @ 2006 </a> | <a href="#">Privacy policy</a></p>
      </div>
    </div>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render "layouts/head_tag_element" %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">

    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <img src="/assets/logo.png"   style="height:50px;width:100px;" />
        </div>
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>

    <div id="main" role="main">
      <div class="container" id="container">
        <div class="content">
          <div class="row">
            <div class="span12">
              <%= yield :header_image %>
            </div> 
            <div class="span12" id="rotate"  style="background:#f0f0f0;color:red;margin-top: 3px;margin-bottom: 3px;padding-top:3px;padding-bottom:3px;">
              <marquee id="FutureMarquee" onmouseup="this.style.cursor=" default''="" onmouseover="this.stop();" onmouseout="this.start();" truespeed="truespeed" scrollamount="1" scrolldelay="20" width="100%" style="font-weight:bold;color:#000; padding-top:2px; display:block;"> Market Pundit Money Making Mantra <strong style="color:green">|</strong> Market Pundit Money Making Mantra <strong style="color:green">|</strong> Market Pundit Money Making MantraMarket Pundit Money Making Mantra <strong style="color:green">|</strong> Market Pundit Money Making Mantra <strong style="color:green">|</strong> Market Pundit Money Making Mantra</marquee>
            </div>
          </div>
          <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
            <%= render "layouts/footer" %>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->

  </body>
</html>